{% macro select_listings_union_cols(source_model, platform) %}
    
    SELECT
        -- 17 Common fixed columns moved to the top
        AS_SOURCE,
        LISTING_ID,
        ASKING_PRICE,
        ADDRESS,
        POSTCODE,
        LATITUDE,
        LONGITUDE,
        PROPERTY_TYPE,
        TRANSACTION_TYPE,
        BEDROOMS,
        BATHROOMS,
        SIZE_SQFEET,
        TENURE,
        DISPLAY_STATUS,
        AGENT_BRANCH_ID,
        SUMMARY_DESCRIPTION,
        DETAILED_DESCRIPTION,
        
        -- Remaining 37 columns, standardized and conditionally selected
        {% if platform == 'ZOOPLA' %}
            LISTING_CHANGE_ID,
            CHANGE_DATE,
            UPRN,
            CHANGE_TYPE,
            PCD_CODE,
            LOCAL_AUTHORITY,
            REGION,
            COUNTRY,
            RECEPTIONS,
            FLOORS,
            RENT_FREQUENCY,
            BULLETS,
            BRANCH_ADDRESS,
            IS_NEW_HOME,
            HAS_BUYER_INCENTIVES,
            IS_SHARED_ACCOMMODATION,
            IS_AUCTION,
            NULL AS UPDATE_REASON,
            NULL AS TRANSACTIONS,
            NULL AS FEATURES,
            NULL AS SNAPSHOT_IMPORT_NAME,
            NULL AS IMPORT_NAME,
            NULL AS PRICE_QUALIFIER,
            NULL AS EPC_BAND,
            NULL AS COUNCIL_TAX,
            NULL AS EPC_DATE,
            NULL AS TIME_SINCE_UPDATE,
            NULL AS RETIREMENT_HOME,
            NULL AS STUDENT_PROPERTY,
            NULL AS SHARED_OWNERSHIP,
            NULL AS AGENT_BRANCH,
            NULL AS LISTING_URL,
            NULL AS RELATED_URLS,
            AGENT_BRAND_ID AS AGENT_BRAND_ID_FIELD_29, -- Re-map AGENT_BRAND_ID if it's used twice in output list
            NULL AS AGENT_BRANCH_FIELD_52,
            NULL AS LISTING_URL_FIELD_53,
            NULL AS RELATED_URLS_FIELD_54
            
        {% elif platform == 'RIGHTMOVE' %}
            NULL AS LISTING_CHANGE_ID,
            NULL AS CHANGE_DATE,
            NULL AS UPRN,
            NULL AS CHANGE_TYPE,
            NULL AS PCD_CODE,
            NULL AS LOCAL_AUTHORITY,
            NULL AS REGION,
            NULL AS COUNTRY,
            NULL AS RECEPTIONS,
            NULL AS FLOORS,
            NULL AS RENT_FREQUENCY,
            NULL AS BULLETS,
            NULL AS BRANCH_ADDRESS,
            NULL AS IS_NEW_HOME,
            NULL AS HAS_BUYER_INCENTIVES,
            NULL AS IS_SHARED_ACCOMMODATION,
            NULL AS IS_AUCTION,
            UPDATE_REASON,
            TRANSACTIONS,
            FEATURES,
            NULL AS SNAPSHOT_IMPORT_NAME,
            IMPORT_NAME,
            NULL AS PRICE_QUALIFIER,
            NULL AS EPC_BAND,
            NULL AS COUNCIL_TAX,
            NULL AS EPC_DATE,
            NULL AS TIME_SINCE_UPDATE,
            NULL AS RETIREMENT_HOME,
            NULL AS STUDENT_PROPERTY,
            NULL AS SHARED_OWNERSHIP,
            AGENT_BRANCH,
            LISTING_URL,
            RELATED_URLS,
            AGENT_BRAND_ID AS AGENT_BRAND_ID_FIELD_29,
            AGENT_BRANCH AS AGENT_BRANCH_FIELD_52,
            LISTING_URL AS LISTING_URL_FIELD_53,
            RELATED_URLS AS RELATED_URLS_FIELD_54

        {% elif platform == 'OTM' %}
            NULL AS LISTING_CHANGE_ID,
            NULL AS CHANGE_DATE,
            UPRN,
            NULL AS CHANGE_TYPE,
            NULL AS PCD_CODE,
            NULL AS LOCAL_AUTHORITY,
            NULL AS REGION,
            NULL AS COUNTRY,
            NULL AS RECEPTIONS,
            NULL AS FLOORS,
            NULL AS RENT_FREQUENCY,
            NULL AS BULLETS,
            NULL AS BRANCH_ADDRESS,
            NULL AS IS_NEW_HOME,
            NULL AS HAS_BUYER_INCENTIVES,
            NULL AS IS_SHARED_ACCOMMODATION,
            NULL AS IS_AUCTION,
            NULL AS UPDATE_REASON,
            NULL AS TRANSACTIONS,
            NULL AS FEATURES,
            SNAPSHOT_IMPORT_NAME,
            IMPORT_NAME,
            PRICE_QUALIFIER,
            EPC_BAND,
            COUNCIL_TAX,
            EPC_DATE,
            TIME_SINCE_UPDATE,
            RETIREMENT_HOME,
            STUDENT_PROPERTY,
            SHARED_OWNERSHIP,
            AGENT_BRANCH,
            LISTING_URL,
            RELATED_URLS,
            AGENT_BRAND_ID AS AGENT_BRAND_ID_FIELD_29,
            AGENT_BRANCH AS AGENT_BRANCH_FIELD_52,
            LISTING_URL AS LISTING_URL_FIELD_53,
            RELATED_URLS AS RELATED_URLS_FIELD_54
            
        {% endif %}

    FROM {{ ref(source_model) }}
    
{% endmacro %}