{{ config(
    materialized='view'
    
) }}

SELECT 
    'OTM' AS AS_SOURCE,
    LISTINGID AS LISTING_ID,
    LISTINGURL AS LISTING_URL,
    TRANSACTIONTYPE AS TRANSACTION_TYPE,
    ADDRESS,
    POSTCODE,
    TRY_TO_NUMBER(BEDROOMS) AS BEDROOMS,
    TRY_TO_NUMBER(BATHROOMS) AS BATHROOMS,
    TRY_TO_NUMBER(REGEXP_SUBSTR(SIZESQFEET, '^[0-9]+')) AS SIZE_SQFEET,
    TRY_TO_NUMBER(ASKINGPRICE) AS ASKING_PRICE,
    PROPERTYTYPE AS PROPERTY_TYPE,
    REGEXP_REPLACE(SUMMARY, '<[^>]+>', '') AS SUMMARY_DESCRIPTION,
    REGEXP_REPLACE(DESCRIPTION, '<[^>]+>', '') AS DETAILED_DESCRIPTION,
    TRY_TO_DOUBLE(LATITUDE) AS LATITUDE,
    TRY_TO_DOUBLE(LONGITUDE) AS LONGITUDE,
    TENURE,
    DISPLAYSTATUS AS DISPLAY_STATUS,
    AGENTBRAND AS AGENT_BRAND,
    TRY_TO_NUMBER(AGENTBRANDID) AS AGENT_BRAND_ID,
    AGENTBRANCH AS AGENT_BRANCH,
    TRY_TO_NUMBER(AGENTBRANCHID) AS AGENT_BRANCH_ID,
    RELATEDURLS AS RELATED_URLS,
    IMPORTNAME AS IMPORT_NAME,
    SNAPSHOTIMPORTNAME,
    PRICEQUALIFIER,
    EPCBAND,
    TRY_TO_DATE(
        NULLIF(TRIM(EPCDATE), ''), 
        'MON DD, YYYY'
    ) AS EPC_DATE,
    COUNCILTAX,
    REGEXP_REPLACE(TIMESINCEUPDATE, '[*|]', ',') AS TIME_SINCE_UPDATE,
    IFF(LOWER(RETIREMENTHOME) = 'true', TRUE, FALSE) AS RETIREMENT_HOME,
    IFF(LOWER(STUDENT) = 'true', TRUE, FALSE) AS STUDENT_PROPERTY,
    IFF(LOWER(SHAREDOWNERSHIP) = 'true', TRUE, FALSE) AS SHARED_OWNERSHIP,
    UPRN
FROM
    
    {{ source('otm', 'snapshot') }}