{{ config(
    materialized='view'
    
) }}

SELECT 
    'RIGHTMOVE' AS AS_SOURCE,
    LISTING_ID,
    TRY_TO_NUMBER(ASKING_PRICE) AS ASKING_PRICE,
    ADDRESS,
    POSTCODE,
    TRY_TO_NUMBER(BEDROOMS) AS BEDROOMS,
    TRY_TO_NUMBER(BATHROOMS) AS BATHROOMS,
    PROPERTY_TYPE,
    REGEXP_REPLACE(SUMMARY, '<[^>]+>', '') AS SUMMARY_DESCRIPTION,
    REGEXP_REPLACE(DESCRIPTION, '<[^>]+>', '') AS DETAILED_DESCRIPTION,
    TRY_TO_DOUBLE(LATITUDE) AS LATITUDE,
    TRY_TO_DOUBLE(LONGITUDE) AS LONGITUDE,
    TENURE,
    TRY_TO_NUMBER(REGEXP_SUBSTR(SIZE_SQ_FEET, '^[0-9]+')) AS SIZE_SQFEET,
    DISPLAY_STATUS,
    AGENT_BRAND,
    TRY_TO_NUMBER(AGENT_BRANCH_ID) AS AGENT_BRANCH_ID,
    AGENT_BRANCH,
    LISTING_URL,
    RELATED_URLS,
    IMPORT_NAME,
    UPDATE_REASON,
    TRANSACTION_TYPE,
    REGEXP_REPLACE(FEATURES, '[*|]', ',') AS FEATURES,
    REGEXP_REPLACE(TRANSACTIONS, '[*|]', ',') AS TRANSACTIONS
FROM
    
    {{ source('rightmove', 'rightmove_listings') }}